### ISSUE TITLE
How to add myself query fnn files and custom's big database?

### ISSUE THREAD

**Issue by wahahaaaa123** [ghzuo/CVTree#1]
Hi,
    I want to use this software for some query FNN files (which I don't know its Lineage) in an all-bacteria complete genome database from NCBI.

So, what I need to do?

1. put my query files(FNN) and NCBI database file (FNN) in the "faa or ffn" folder.
2. list their names to 'list' file 
3. run runCVTree.sh

**Comment by ghzuo** [comment]
Hi, liji

Yes, you can run the program by using the runCVTree.sh script. 
There is a example in the "example" directory. Beside the items 
list in your message. You need compile the program, and change 
the values of variable "gytpe" and "gdir" in the runCVTree.sh script,
before you run the script.

And as a suggestion, you can try our web server:
http://tlife.fudan.edu.cn/cvtree
It is much more powerful than the software, and more fiendly. 

Guanghong
