### ISSUE TITLE
 the frequency of appearance of the K-string.

### ISSUE THREAD

**Issue by zhibaosuo** [ghzuo/CVTree#2]
I wonder if I can see the frequency of appearance of the K-string in the given protein sequence specifically.

**Comment by ghzuo** [comment]
You can see it by cvdump.


 
---Original---

**Comment by zhibaosuo** [comment]
If the output result of the cvdump is the difference between the actual counting result p and the predicted value p0? And I want to use the "-n" to write the result to the out file, but I only get the screen output, how can I solve this problem?

**Comment by ghzuo** [comment]
You can use the g2cv with the option "-m Count".

**Comment by zhibaosuo** [comment]
Okay, I will try, Thank you !
