### ISSUE TITLE
bootstrapping from Docker version

### ISSUE THREAD

**Issue by jlac** [ghzuo/CVTree#8]
I see in this repo that bootstrapping appears to be added, but the Docker version predates the version in the repo. Could you please update the Docker version of cvtree so I can install the most up to date code with bootstrapping? Also, it is unclear from the manual or example how to run the bootstrapping portion. Can you provide details for doing this?

Justin

**Comment by ghzuo** [comment]
I am sorry. I can't login the dockerhub at the moment for some reason.
But I had updated the dockerfile at github for branch bootstrap.&nbsp;
So you can build the image by yourself. And you can get help info about bootstrap
by use "cvtree -h". There are two options "-S and -b" for bootstrapping.


In fact, we are working on the bootstrap method. So this is may be not the final
version for the bootstrap of cvtree.&nbsp;&nbsp;

Best regards,&nbsp;Guanghong&nbsp;
-------------------------------------------------------------------
Guanghong Zuo Ph.D (左光宏）
Wenzhou Institute,&nbsp;
University of Chinese Academy of Sciences
Wenzhou, Zhejiang 325001, China
Email: ***@***.***; ***@***.***
-------------------------------------------------------------------

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ghzuo/CVTree"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月13日(星期天) 凌晨0:47
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ghzuo/CVTree] bootstrapping from Docker version (Issue #8)





 
I see in this repo that bootstrapping appears to be added, but the Docker version predates the version in the repo. Could you please update the Docker version of cvtree so I can install the most up to date code with bottstrapping? Also, it is unclear from the manual or example how to run the bootstrapping portion. Can you provide details for doing this?
 
Justin

**Comment by ghzuo** [comment]
I had just push the bootstrapping cvtree.&nbsp;
Now you can get it from dockerhub with tag "bootstrap".



Best regards,&nbsp;Guanghong&nbsp;
-------------------------------------------------------------------
Guanghong Zuo Ph.D (左光宏）
Wenzhou Institute,&nbsp;
University of Chinese Academy of Sciences
Wenzhou, Zhejiang 325001, China
Email: ***@***.***; ***@***.***
-------------------------------------------------------------------

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ghzuo/CVTree"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月13日(星期天) 凌晨0:47
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ghzuo/CVTree] bootstrapping from Docker version (Issue #8)





 
I see in this repo that bootstrapping appears to be added, but the Docker version predates the version in the repo. Could you please update the Docker version of cvtree so I can install the most up to date code with bottstrapping? Also, it is unclear from the manual or example how to run the bootstrapping portion. Can you provide details for doing this?
 
Justin
